version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: todo_app 
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    depends_on:
      db:
        condition: service_healthy 

  nginx:
    image: nginx:alpine
    container_name: todo_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: